// Generated by Enterprise IDE Plugin from IDE factory L.L.C.
package net.kolektiv.proto.mvc
{

	public class Controller 
	{
		protected var model:Model;
		protected var view:View;
		
		public function Controller(model:Model){
		 	this.model = model;
		 }
	}

}